function data
% DATA  Aircraft data used throughout the project.
%
% This function defines the aicrcraft data used throughout the project,
% and write them in `data.mat`.
%
% NOTE:
% This file should not exist. It should be removed, once all the matlab
% code is integrated and write themselves in data.mat.

%% Imports

% Directory where the present file lies.
file_dir = fileparts(mfilename("fullpath"));

% Constants.
C = load(fullfile(file_dir, "../constants.mat"));

%% Plane

Plane.MTOW = 3612.73743;  % MTOW [kg].

%% Wing

%Wing planform.
Wing.AR       = 8;         % Aspect ratio.
Wing.lambda   = 0.35;      % Taper ratio.
Wing.S        = 7.3686;    % Surface area [m²].
Wing.b        = 7.6778;    % Span [m].
Wing.c_r      = 1.4218;    % Chord at root [m].
Wing.c_t      = 0.4976;    % Chord at tip [m].
Wing.smc      = 0.9597;    % Standard mean chord [m].
Wing.mac      = 1.0338;    % Mean Aerodynamic Chord [m].
Wing.y_ac     = 1.6114;    % Spanwise position of MAC [m].
Wing.twist    = -1;        % Aerodynamic twist (washout) [°].
Wing.sweep    = 24;        % Quarter-chord sweep angle [°].
Wing.mass     = 188.96;    % Dry mass of wing [kg].
Wing.Vol_fuel = 0.370253;  % Volume of fuel in wing [m³].
Wing.cg_mac   = 30;        % Position of the CG of the wing at MAC w.r.t. the LE [%].
Wing.S_wet    = 15.1793;   % Wetted surface area [m²].
Wing.e        = 0.6164;    % Oswald's span efficiency.

% Wing Lift characteristics.
Wing.CL_alpha      = 5.6909;   % Slope of the lift coefficient of the wing [1/rad].
Wing.aoa_zerolift  = -1.7672;  % Zero-lift angle of attack at root [°].
Wing.aoa_midcruise = 0.5044;   % Angle of attack at root at mid-cruise [°].
Wing.i             = 0.9241;   % Angle of incidence of the wing [°].
Wing.CL_cr         = 0.276;    % Refined Lift coefficient at cruise (MTOW) [-].

% Wing drag characteristics.
Wing.CD_0 = 0.017;  % Zero lift drag coefficient.

% Stall behaviour.
Wing.CL_max               = 1.4927;   % Wing max lift coefficient in clean configuration [-].
Wing.CL_max_takeoff       = 2.0397;   % Wing max lift coefficient at takeoff [-].
Wing.CL_max_landing       = 2.1723;   % Wing max lift coefficient at landing [-].
Wing.V_s_takeoff          = 55.1174;  % Stall velocity in takeoff configuration (MTOW) [m/s].
Wing.V_s_landing          = 36.2724;  % Stall velocity in landing configuration [m/s].
Wing.V_s_landing_mtow     = 53.409;   % Stall velocity in landing configuration (MTOW) [m/s].
Wing.delta_cl_max_takeoff = 0.55;     % Delta max lift coeff at takeoff.
Wing.delta_cl_max_landing = 0.68;     % Delta max lift coeff at landing.

% Airfoil profile.
Wing.airfoil.name         = "NASA SC(2)-0412";
Wing.airfoil.tc_ratio     = 0.12;     % Thickness to chord ratio [-].
Wing.airfoil.cl_alpha     = 10.2106;  % Slope of the lift coefficient [1/rad].
Wing.airfoil.cl_max       = 1.72;     % Max lift coefficient (incompressible) [-].
Wing.airfoil.aoa_zerolift = -2.022;   % Zero-lift angle of attack of the airfoil [°].
Wing.airfoil.M_dd         = 0.786;    % Drag divergence mach number [-].
Wing.airfoil.C_m          = -0.0778;  % Pitching moment coefficient (incompressible) [-].

% Flaps planform: plain flaps.
% Begins at the end of fuselage width + 2% of span
% Ends at 60% of span
% 25% of the airfoil chord
Wing.flaps.defl_takeoff = 20; % Flap deflection at takeoff [°].
Wing.flaps.defl_landing = 40; % Flap deflection at landing [°].

% Ailerons planform.
% Begins at 60% of span
% Ends at 90% of span
% 25% of the airfoil chord

%% Tail

% TODO: encode tail data.

%% Propulsion

% Propu structure, generated by Propulsion/propulsion.m.

%% Flight envelope

% FE structure, generated by Structure/flight_envelope.m

%% Components

Comp = table( ...
	'Size',          [0, 3], ...
	'VariableTypes', {'double', 'double', 'double'}, ...
	'VariableNames', {'Weight', 'CG_x',   'CG_z'  });

Comp("Fuselage",                    :) = {1250.1,      3.6,    0.5};
Comp("Main_landing_gear",           :) = {379.4461,    4.7,    0.5};
Comp("Nose_landing_gear",           :) = {79.7383,     1.5,    0.5};
Comp("Engine_mount",                :) = {6.7189,      7.13,   0.5};
Comp("Engine_section",              :) = {4.782,       7.13,   0.5};
Comp("Air_induction_system",        :) = {333.1425,    4.48,   0.5};
Comp("Tail_pipe",                   :) = {4.7075,      7.75,   0.5};
Comp("Starter",                     :) = {12.65,       6.48,   0.5};
Comp("Fuel system and empty tanks", :) = {11.087,      3.6028, 0.5};
Comp("Instruments",                 :) = {83.49,       3.5,    0.5};
Comp("Hydraulics",                  :) = {171.7485,    4.5,    0.5};
Comp("Furnishings",                 :) = {108.8,       1.5,    0.5};
Comp("Handling gear",               :) = {0.6596,      1.5,    0.5};
Comp("Empennage vertical",          :) = {29.63,       7.309,  0.5};
Comp("Empennage horizontal",        :) = {14.68,       7.6474, 0.5};
Comp("Wings",                       :) = {414.83,      4.1528, 0.5};
Comp("Fuel Wing",                   :) = {669.353613,  4.1528, 0.5};
Comp("Fuel fuselage",               :) = {3188.731387, 4.1528, 0.5};
Comp("Payload",                     :) = {300,         4.1528, 0.5};
Comp("Engine",                      :) = {670.21,      7.13,   0.5};
Comp("Flight control unit",         :) = {20,          3,      0.5};
Comp("System control unit",         :) = {18,          3,      0.5};
Comp("Flight transduces",           :) = {3,           4.4202, 0.5};
Comp("Power engine control unit",   :) = {7,           7.13,   0.5};
Comp("Power converter assembly",    :) = {4,           7.13,   0.5};
Comp("GPS receiver (anti-jam)",     :) = {25,          1.5,    0.5};
Comp("GPS antenna",                 :) = {6,           1.5,    0.5};
Comp("Battery (non-propulsion)",    :) = {13,          1.5,    0.5};
Comp("Cooling and pressurization",  :) = {5,           2.6,    0.5};
Comp("Air data probe",              :) = {1,           4.47,   0.5};
Comp("Anti-ice",                    :) = {2,           1,      0.5};
Comp("Thermal management",          :) = {23,          2.5,    0.5};
Comp("Miscelectrical wiring",       :) = {5,           2,      0.5};
Comp("Basic satellite radio",       :) = {34,          2.5,    0.5};
Comp("Data handling and linking",   :) = {24,          2.5,    0.5};
Comp("Flight termination system",   :) = {10,          2,      0.5};
Comp("Navigation fusion processor", :) = {9,           2,      0.5};
Comp("Transponders",                :) = {15,          1.5,    0.5};
Comp("Radar",                       :) = {63,          0.75,   0.5};
Comp("Nose EO/IR/LIDAR",            :) = {100,         1,      0.5};
Comp("Aft EO/IR/LIDAR",             :) = {50,          6.5,    0.5};
Comp("Sensor growth",               :) = {15,          1.5,    0.5};

% Convert weights from lb to kg.
Comp(:, "Weight") = array2table(Comp{:, "Weight"} .* C.lb2kg);

%% Write in data.mat

% Save data in data.mat, which lies in the root directory.
save(fullfile(file_dir, "../data.mat"), "Plane", "Wing", "Comp");

end
